import asyncio
import glob
import hashlib
import logging
import os
import re
import shlex
import typing
from . import transformations


LOGGER = logging.getLogger(__name__)


class Artifact:
    """
    Artifact generated by a transformation.

    Args:
        name: Unique name of the artifact.

    Attrs:
        parent: Transformation that generates this artifact; :code:`None` if the artifact is a root
            of the directed acyclic graph.
        children: Transformations that consume this artifact; empty if the artifact is a leaf of the
            directed acyclic graph.
        digest: Concise summary of the artifact.
    """
    def __init__(self, name: str) -> None:
        if self.REGISTRY.setdefault(name, self) is not self:
            raise RuntimeError(f"artifact with name `{name}` already exists")
        self.name = name
        self._parent = None
        self.children = []

    @property
    def parent(self) -> 'transformations.Transformation':
        return self._parent

    @parent.setter
    def parent(self, value: 'transformations.Transformation') -> None:
        if self._parent is not None:
            raise RuntimeError(f"{self} is already associated with a transformation")
        self._parent = value

    @property
    def digest(self) -> bytes:
        return None

    def __repr__(self):
        return f"{self.__class__.__name__}({self.name})"

    async def __call__(self):
        if self.parent is None:
            return
        return await self.parent

    def __await__(self):
        # See https://stackoverflow.com/a/57078217/1150961 for details.
        return (yield from self().__await__())

    REGISTRY = {}


class File(Artifact):
    """
    Artifact representing a file.
    """
    def __init__(self, name: str) -> None:
        super().__init__(name)
        self.filename = os.path.abspath(name)
        if re.search(r"\s", self.filename):
            LOGGER.warning("whitespace in `%s` is a recipe for disaster; expect the unexpected",
                           self.filename)
        self._last_modified = None
        self._digest = None

    async def __call__(self):
        await super().__call__()
        if not os.path.exists(self.filename):
            if self._parent:
                message = f"{self._parent} did not generate {self}"
            else:
                message = f"{self} does not exist and cannot be generated"
            raise FileNotFoundError(message)

    @property
    def digest(self):
        try:
            # Only re-evaluate the digest if the file has not been modified since we last computed
            # the hash.
            last_modified = os.stat(self.filename).st_mtime
            if self._last_modified is None or self._last_modified < last_modified:
                algorithm = hashlib.sha256()
                with open(self.filename, 'rb') as fp:
                    while (chunk := fp.read(4096)):
                        algorithm.update(chunk)
                self._digest = algorithm.digest()
                self._last_modified = last_modified
            return self._digest
        except FileNotFoundError:
            return None

    @classmethod
    def glob(self, pattern):
        """
        Create a list of file artifacts based on a glob pattern.

        Args:
            pattern: Pattern passed to :func:`glob.glob`.

        Returns:
            artifacts: List of file artifacts.
        """
        return normalize_artifacts([filename for filename in glob.glob(pattern)])

    def __str__(self):
        return shlex.quote(self.filename)


def normalize_artifacts(artifacts) -> typing.Iterable[Artifact]:
    """
    Normalize one or more artifacts. Strings are implicitly converted to :class:`FileArtifact`s.

    Args:
        artifacts: One or more artifacts.

    Returns:
        normalized: List of normalized artifacts.
    """
    if artifacts is None:
        return []
    if not isinstance(artifacts, typing.Iterable) or isinstance(artifacts, str):
        artifacts = [artifacts]
    normalized = []
    for artifact in artifacts:
        if isinstance(artifact, str):
            try:
                candidate = Artifact.REGISTRY[artifact]
                if isinstance(candidate, File):
                    artifact = candidate
                else:
                    raise ValueError("only file artifacts can be implicitly referenced by name")
            except KeyError:
                artifact = File(artifact)
        elif not isinstance(artifact, Artifact):
            raise TypeError(artifact)
        normalized.append(artifact)
    return normalized


async def gather_artifacts(*artifacts, num_concurrent: int = None):
    """
    Gather one or more artifacts and wrap them in a coroutine.
    """
    if num_concurrent is not None:
        transformations.Transformation.SEMAPHORE = asyncio.Semaphore(num_concurrent)
    await asyncio.gather(*(artifact for artifact in artifacts))
